if(NOT DEFINED WLCOM_WLROOTS_VENDOR_SOURCE_DIR)
  message(FATAL_ERROR "WLCOM_WLROOTS_VENDOR_SOURCE_DIR is required")
endif()

if(NOT DEFINED WLCOM_WLROOTS_SOURCE_DIR)
  message(FATAL_ERROR "WLCOM_WLROOTS_SOURCE_DIR is required")
endif()

if(NOT DEFINED WLCOM_WLROOTS_OVERLAY_DIR)
  message(FATAL_ERROR "WLCOM_WLROOTS_OVERLAY_DIR is required")
endif()

file(REMOVE_RECURSE "${WLCOM_WLROOTS_SOURCE_DIR}")
file(MAKE_DIRECTORY "${WLCOM_WLROOTS_SOURCE_DIR}")
file(COPY "${WLCOM_WLROOTS_VENDOR_SOURCE_DIR}/"
  DESTINATION "${WLCOM_WLROOTS_SOURCE_DIR}"
)

file(COPY "${WLCOM_WLROOTS_OVERLAY_DIR}/"
  DESTINATION "${WLCOM_WLROOTS_SOURCE_DIR}"
)
